services:
  client:
    build:
      context: ./client_HotelBooking
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client_HotelBooking:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  admin:
    build:
      context: ./admin_HotelBoking
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./admin_HotelBoking:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  server:
    build:
      context: ./server_HotelBooking
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server_HotelBooking:/app
      - /app/node_modules
    environment:
      NODE_ENV: development